@baseUrl = http://localhost:3000
@token = {{"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NjUxMTU0MiwiZXhwIjoxNzQ5MTAzNTQyfQ.HIAbG8kdXPI6lXBBOgcB-SLw7T5VsCBjrpEVRitgC50"}}


### Create a new client
POST {{baseUrl}}/clients/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Delete Doe",
  "email": "Delete@example.com",
  "phone": "987456123"
}


### Get all clients
GET {{baseUrl}}/clients/
Authorization: Bearer {{token}}


### Get a client by ID
GET {{baseUrl}}/clients/1
Authorization: Bearer {{token}}



### Update a client
PUT {{baseUrl}}/clients/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.Doe@example.com",
  "phone": "9876543210"
}


### Delete a client
PUT {{baseUrl}}/clients/delete/3
Authorization: Bearer {{token}}