@baseUrl = http://localhost:3000
@token = {{"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NjIzNjAyMiwiZXhwIjoxNzQ4ODI4MDIyfQ.Jc8lf2Ipx2NnB1X5DVBt4KpTdCfadge-lqh8ZvKvHUY"}}


GET {{baseUrl}}/invoices/get-invoice/2
Authorization: Bearer {{token}}
Accept: application/json


