@baseUrl = http://localhost:3000
@token = {{"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NjIzNjAyMiwiZXhwIjoxNzQ4ODI4MDIyfQ.Jc8lf2Ipx2NnB1X5DVBt4KpTdCfadge-lqh8ZvKvHUY"}}



### ✅ Create Invoice
POST {{baseUrl}}/invoices/create-invoice
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "clientName": "Mark",
  "client": 1,
  "amount": 1500.50,
  "dueDate": "2025-06-01T00:00:00Z"
}